insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (48,'Antonio','Koper');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (47,'Tomasa','Orouke');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (46,'Belinda','Barger');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (45,'Gladys','Laughery');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (44,'Ginger','Zorman');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (43,'Sabine','Bonaguidi');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (41,'Anton','Mew');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (42,'Annmarie','Esmay');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (38,'Ruthanne','Burgoyne');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (39,'Gisele','Limthong');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (40,'Benedict','Lavery');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (34,'Glenn','Mcgraff');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (35,'Antonia','Mclachlan');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (36,'Basil','Hanagan');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (37,'Anneliese','Namdar');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (27,'Bebe','Broadwell');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (28,'Florida','Gilliand');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (29,'Fran','Sibbald');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (30,'Becky','Falsetti');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (31,'Gilberto','Weibel');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (32,'Ruthe','Nishioka');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (33,'Belva','Old');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (16,'Tommy','Stoor');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (17,'Veronica','Aubrecht');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (18,'Beatris','Iraheta');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (19,'Gladis','Trevey');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (20,'Basil','Oursler');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (21,'Therese','Zaeske');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (22,'Bella','Osterfeld');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (23,'Francesco','Elland');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (24,'Bart','Detullio');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (25,'Wynona','Tenda');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (26,'Judson','Kantz');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (49,'Antonetta','Pinsky');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (0,'Theodora','Beavin');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (1,'Annetta','Juback');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (2,'Floy','Craver');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (3,'Tyrell','Zuelke');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (4,'Sabrina','Stojanovic');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (5,'Yvonne','Appleman');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (6,'Beau','Deerman');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (7,'Ty','Flournay');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (8,'Antoine','Applonie');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (9,'Belen','Ogden');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (10,'Vernita','Kulik');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (11,'Annice','Mccrossen');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (12,'Beata','Ladieu');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (13,'Toccara','Konwinski');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (14,'Julian','Rudack');
insert into ALMACEN (NRO,NOMBRE,RESPONSABLE) values (15,'Ryan','Montori');
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (0, 'Camiseta sin mangas - M', 450.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (1, 'Camisa polo - XL', 1750.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (2, 'Contenedor plástico de almacenamiento', 500.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (3, 'Gorro de lana', 650.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (4, 'Medias', 690.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (5, 'Camiseta sin mangas - S', 450.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (6, 'Medias deportivas', 900.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (7, 'Organizador de cajones plástico', 450.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (8, 'Contenedor plástico de almacenamiento', 2000.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (9, 'Carpeta de 3 anillos', 1400.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (10, 'Tapete para cocina - L', 650.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (11, 'Medias deportivas', 450.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (13, 'Bloc de dibujo con espiral', 600.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (14, 'Camiseta - XL', 750.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (15, 'Carpeta de 3 anillos', 2100.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (16, 'Pequeño bloc de notas', 400.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (17, 'Tapete para cocina - M', 650.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (18, 'Contenedor plástico de almacenamiento (Individual)', 250.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (19, 'Camisa de franela manga larga - M', 1100.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (20, 'Carpeta de 3 anillos', 700.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (21, 'Medias deportivas', 150.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (22, 'Camiseta sin mangas - L', 450.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (23, 'Contenedor plástico de almacenamiento', 3000.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (24, 'Buzo con cierre - S', 2500.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (25, 'Camiseta - S', 750.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (26, 'Camisa polo - L', 1750.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (27, 'Carpeta de 3 anillos', 350.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (28, 'Buzo con cierre - XL', 2500.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (29, 'Raqueta de bádminton', 800.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (30, 'Camiseta sin mangas - XL', 450.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (31, 'Pelotas de golf', 500.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (32, 'Camisa de franela manga larga - L', 1100.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (33, 'Camisa de franela manga larga - S', 1100.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (34, 'Medias', 115.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (35, 'Libro de bocetos encuadernado', 800.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (36, 'Tapete para cocina - XL', 650.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (37, 'Camiseta - M', 750.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (38, 'Tapete para cocina - S', 650.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (39, 'Pelotas de golf', 3000.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (40, 'Camisa polo - S', 1750.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (41, 'Vaso antiderrame para niños', 350.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (42, 'Camisa de franela manga larga - XL', 1100.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (43, 'Camisa polo - M', 1750.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (44, 'Carpeta de 3 anillos (Individual)', 175.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (45, 'Buzo con cierre - L', 2500.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (46, 'Camiseta - L', 750.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (47, 'Buzo con cierre - M', 2500.00);
INSERT INTO ARTICULO (COD_ART, DESCRIPCION, PRECIO) VALUES (48, 'Pelotas de golf', 1500.00);
insert into MATERIAL (COD_MAT,DESCRIPCION) values (0,'Technetium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (1,'Berkelium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (2,'Tungsten');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (3,'Thorium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (4,'Einsteinium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (5,'Ununquadium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (6,'Neptunium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (7,'Seaborgium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (8,'Plutonium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (9,'Rhenium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (10,'Uranium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (11,'Cadmium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (12,'Polonium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (13,'Ununpentium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (14,'Francium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (15,'Iridium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (16,'Palladium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (17,'Americium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (18,'Roentgenium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (19,'Gold');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (20,'Indium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (21,'Radium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (22,'Mendelevium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (23,'Lead');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (24,'Platinum');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (25,'Osmium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (26,'Hassium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (27,'Rhodium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (28,'Nobelium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (29,'Darmstadtium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (30,'Dubnium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (31,'Astatine');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (32,'Niobium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (33,'Lawrencium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (34,'Radon');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (35,'Ununtrium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (36,'Molybdenum');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (37,'Californium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (38,'Meitnerium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (39,'Bismuth');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (40,'Mercury');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (41,'Protactinium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (42,'Thallium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (43,'Curium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (44,'Fermium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (45,'Bohrium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (46,'Silver');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (47,'Ununbium');
insert into MATERIAL (COD_MAT,DESCRIPCION) values (48,'Ruthenium');
insert into CIUDAD (COD_CIU,NOMBRE) values (0,'Minneapolis');
insert into CIUDAD (COD_CIU,NOMBRE) values (1,'Colorado Springs');
insert into CIUDAD (COD_CIU,NOMBRE) values (2,'Black Hawk');
insert into CIUDAD (COD_CIU,NOMBRE) values (3,'Helena');
insert into CIUDAD (COD_CIU,NOMBRE) values (4,'Burbank');
insert into CIUDAD (COD_CIU,NOMBRE) values (5,'Wolcott');
insert into CIUDAD (COD_CIU,NOMBRE) values (6,'Wessington');
insert into CIUDAD (COD_CIU,NOMBRE) values (7,'Burnsville');
insert into CIUDAD (COD_CIU,NOMBRE) values (8,'Mesa');
insert into CIUDAD (COD_CIU,NOMBRE) values (9,'Bighorn');
insert into CIUDAD (COD_CIU,NOMBRE) values (10,'Sandy');
insert into CIUDAD (COD_CIU,NOMBRE) values (11,'Ketchum');
insert into CIUDAD (COD_CIU,NOMBRE) values (12,'Webster');
insert into CIUDAD (COD_CIU,NOMBRE) values (13,'Lava Hot Springs');
insert into CIUDAD (COD_CIU,NOMBRE) values (14,'Denver');
insert into CIUDAD (COD_CIU,NOMBRE) values (15,'Coffee Creek');
insert into CIUDAD (COD_CIU,NOMBRE) values (16,'West Yellowstone');
insert into CIUDAD (COD_CIU,NOMBRE) values (17,'Algodones');
insert into CIUDAD (COD_CIU,NOMBRE) values (18,'Kanab');
insert into CIUDAD (COD_CIU,NOMBRE) values (19,'Tucson');
insert into CIUDAD (COD_CIU,NOMBRE) values (20,'Boise');
insert into CIUDAD (COD_CIU,NOMBRE) values (21,'Saint Cloud');
insert into CIUDAD (COD_CIU,NOMBRE) values (22,'Coleridge');
insert into CIUDAD (COD_CIU,NOMBRE) values (23,'Joliet');
insert into CIUDAD (COD_CIU,NOMBRE) values (24,'Chino');
insert into CIUDAD (COD_CIU,NOMBRE) values (25,'Eureka');
insert into CIUDAD (COD_CIU,NOMBRE) values (26,'Leonard');
insert into CIUDAD (COD_CIU,NOMBRE) values (27,'Ypsilanti');
insert into CIUDAD (COD_CIU,NOMBRE) values (28,'Steamboat Springs');
insert into CIUDAD (COD_CIU,NOMBRE) values (29,'Duluth');
insert into CIUDAD (COD_CIU,NOMBRE) values (30,'Flaxton');
insert into CIUDAD (COD_CIU,NOMBRE) values (31,'Chicago');
insert into CIUDAD (COD_CIU,NOMBRE) values (32,'Star');
insert into CIUDAD (COD_CIU,NOMBRE) values (33,'San Manuel');
insert into CIUDAD (COD_CIU,NOMBRE) values (34,'Peever');
insert into CIUDAD (COD_CIU,NOMBRE) values (35,'Cochiti Pueblo');
insert into CIUDAD (COD_CIU,NOMBRE) values (36,'Cheyenne');
insert into CIUDAD (COD_CIU,NOMBRE) values (37,'Medicine Bow');
insert into CIUDAD (COD_CIU,NOMBRE) values (38,'Alamo');
insert into CIUDAD (COD_CIU,NOMBRE) values (39,'Iroquois');
insert into CIUDAD (COD_CIU,NOMBRE) values (40,'Rosebud');
insert into CIUDAD (COD_CIU,NOMBRE) values (41,'Cayuga');
insert into CIUDAD (COD_CIU,NOMBRE) values (42,'Sioux Falls');
insert into CIUDAD (COD_CIU,NOMBRE) values (43,'Butte');
insert into CIUDAD (COD_CIU,NOMBRE) values (44,'Saint Ignatius');
insert into CIUDAD (COD_CIU,NOMBRE) values (45,'Yuma');
insert into CIUDAD (COD_CIU,NOMBRE) values (46,'Hyrum');
insert into CIUDAD (COD_CIU,NOMBRE) values (47,'Lisbon');
insert into CIUDAD (COD_CIU,NOMBRE) values (48,'Red Valley');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (0, 'Zorman, Ginger', '2515 SUMMER STREET', 38, '2012-03-21 02:52:58');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (1, 'Beavin, Theodora', 'PO BOX 2210', 42, '2020-02-24 22:55:12');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (2, 'Juback, Annetta', 'PO BOX 2829', 25, '1931-12-18 11:33:31');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (3, 'Gilliand, Florida', '123 S LINCOLN ST', 18, '1927-04-12 18:16:43');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (4, 'Weibel, Gilberto', 'SELECTMAN''S OFFICE', 47, '2016-07-19 20:55:26');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (5, 'Barger, Belinda', 'PO BOX 60', 45, '1998-01-14 23:08:51');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (6, 'Konwinski, Toccara', '2301 PEGER ROAD', 41, '1981-08-20 18:49:33');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (7, 'Mew, Anton', '3375 AIRPORT ROAD', 20, '2007-12-18 10:32:42');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (8, '', '2301 PEGER RD', 5, '1988-02-10 04:19:20');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (9, 'Craver, Floy', '3824 MOBERG DRIVE, STE. 101', 7, '2019-10-06 19:00:58');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (10, 'Nishioka, Ruthe', 'BOX 1180', 12, '1977-03-28 08:53:23');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (11, 'Falsetti, Becky', '2301 PEGER RD', 43, '1957-08-03 15:29:11');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (12, 'Flournay, Ty', 'PO BOX 112506', 29, '1974-05-22 05:40:18');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (13, 'Sibbald, Fran', 'LEWISTON-NEZ PERCE COUNTY AIRPORT, 406 BURRELL AVE., SUITE 301', 21, '1986-05-28 05:53:19');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (14, 'Mccrossen, Annice', '6510 SE FORBES AVE #1', 30, '2004-12-17 13:03:05');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (15, 'Osterfeld, Bella', '1891-9TH ST/BROOKLEY COMPLEX', 26, '2011-07-31 16:34:37');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (16, 'Appleman, Yvonne', 'CITY HALL', 46, '2002-02-16 09:59:28');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (17, 'Rudack, Julian', '2300 WEST WASHINGTON AVE', 15, '1935-02-03 08:22:35');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (18, 'Limthong, Gisele', '1960 JOE CROSSON DRIVE', 24, '2002-02-22 12:20:11');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (19, 'Trevey, Gladis', '2525 HWY 75, SUITE 301', 17, '1954-01-17 03:01:49');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (20, 'Broadwell, Bebe', 'PO BOX 1898', 32, '2005-01-20 09:27:54');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (21, 'Stojanovic, Sabrina', '2301 PEGER RD', 48, '1931-04-25 23:10:27');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (22, 'Lavery, Benedict', '10 PUBLIC SQUARE', 3, '1925-06-28 15:43:16');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (23, 'Deerman, Beau', '2301 PEGER RD', 40, '1968-03-03 07:34:28');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (24, 'Zaeske, Therese', 'HONOLULU INTL ARPT', 23, '2022-12-16 08:51:18');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (25, 'Iraheta, Beatris', 'BOX 390', 19, '2022-04-18 01:34:54');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (26, 'Laughery, Gladys', '18374 PHANTOM', 28, '2012-11-18 02:25:01');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (27, 'Burgoyne, Ruthanne', '100 WEST WASHINGTON ST', 13, '1961-11-13 17:45:11');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (28, 'Applonie, Antoine', '11013 AIRPORT HWY', 14, '1998-01-13 18:49:59');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (29, 'Kantz, Judson', '425 N RICHARDSON', 34, '1942-04-25 15:43:11');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (30, 'Pinsky, Antonetta', 'GOGEBIC CO COURTHOUSE, 200 N MOORE ST', 35, '1985-11-03 05:21:06');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (31, 'Old, Belva', 'BOX 1059', 44, '1990-06-09 21:03:10');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (32, 'Esmay, Annmarie', '3800 AIRPORT ROAD, SUITE 209', 9, '1941-12-09 17:49:53');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (33, 'Stoor, Tommy', 'PO BOX 158', 6, '2006-01-28 01:32:08');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (34, 'Orouke, Tomasa', '148 AVIATION LANE, SUITE 103', 11, '1950-02-03 21:19:58');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (35, 'Tenda, Wynona', '155 BURR STREET', 39, '2015-08-17 01:20:11');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (36, 'Mclachlan, Antonia', '8500 GARFIELD RD STE 101', 27, '1957-07-11 07:18:50');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (37, 'Oursler, Basil', '50 STATE ST, STE 7', 0, '2022-08-17 20:23:49');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (38, 'Kulik, Vernita', '1449 AIRPORT ROAD', 2, '2001-06-28 20:40:23');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (39, 'Elland, Francesco', '602 S. MAIN STREET', 8, '1933-08-21 06:43:12');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (40, 'Montori, Ryan', '1395 N US HIGHWAY 31', NULL, '1966-09-27 16:53:10');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (41, 'Zuelke, Tyrell', '55 INTERNATIONAL DRIVE', 10, '1987-05-22 14:02:28');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (42, 'Detullio, Bart', 'ONE HARBORSIDE DR', 37, '1993-06-23 17:37:07');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (43, 'Mcgraff, Glenn', '2301 PEGER RD', 31, '1938-03-19 03:41:58');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (44, 'Bonaguidi, Sabine', '1550 45TH AVE SE SUITE 1', 4, '1986-11-11 20:08:13');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (45, 'Hanagan, Basil', '6860 GLACIER HIGHWAY', 16, '1959-11-02 19:30:14');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (46, 'Aubrecht, Veronica', '', 36, '2000-06-30 16:37:01');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (47, 'Ladieu, Beata', '3250 W BRITT DAVID RD', 33, '1988-09-16 16:49:20');
INSERT INTO PROVEEDOR (COD_PROV, NOMBRE, DOMICILIO, COD_CIU, FECHA_ALTA) VALUES (48, 'Ogden, Belen', 'PO BOX 398', 22, '2006-12-15 12:18:23');
insert into CONTIENE (NRO,COD_ART) values ('27','38');
insert into CONTIENE (NRO,COD_ART) values ('46','46');
insert into CONTIENE (NRO,COD_ART) values ('17','32');
insert into CONTIENE (NRO,COD_ART) values ('47','31');
insert into CONTIENE (NRO,COD_ART) values ('38','0');
insert into CONTIENE (NRO,COD_ART) values ('3','17');
insert into CONTIENE (NRO,COD_ART) values ('23','42');
insert into CONTIENE (NRO,COD_ART) values ('9','13');
insert into CONTIENE (NRO,COD_ART) values ('6','2');
insert into CONTIENE (NRO,COD_ART) values ('7','34');
insert into CONTIENE (NRO,COD_ART) values ('45','19');
insert into CONTIENE (NRO,COD_ART) values ('42','14');
insert into CONTIENE (NRO,COD_ART) values ('40','9');
insert into CONTIENE (NRO,COD_ART) values ('25','30');
insert into CONTIENE (NRO,COD_ART) values ('29','18');
insert into CONTIENE (NRO,COD_ART) values ('16','28');
insert into CONTIENE (NRO,COD_ART) values ('21','25');
insert into CONTIENE (NRO,COD_ART) values ('15','11');
insert into CONTIENE (NRO,COD_ART) values ('35','47');
insert into CONTIENE (NRO,COD_ART) values ('8','7');
insert into CONTIENE (NRO,COD_ART) values ('32','43');
insert into CONTIENE (NRO,COD_ART) values ('4','5');
insert into CONTIENE (NRO,COD_ART) values ('43','40');
insert into CONTIENE (NRO,COD_ART) values ('34','44');
insert into CONTIENE (NRO,COD_ART) values ('1','10');
insert into CONTIENE (NRO,COD_ART) values ('44','33');
insert into CONTIENE (NRO,COD_ART) values ('20','8');
insert into CONTIENE (NRO,COD_ART) values ('11','22');
insert into CONTIENE (NRO,COD_ART) values ('14','21');
insert into CONTIENE (NRO,COD_ART) values ('24','39');
insert into CONTIENE (NRO,COD_ART) values ('12','45');
insert into CONTIENE (NRO,COD_ART) values ('18','23');
insert into CONTIENE (NRO,COD_ART) values ('33','24');
insert into CONTIENE (NRO,COD_ART) values ('0','37');
insert into CONTIENE (NRO,COD_ART) values ('36','16');
insert into CONTIENE (NRO,COD_ART) values ('5','48');
insert into CONTIENE (NRO,COD_ART) values ('13','1');
insert into CONTIENE (NRO,COD_ART) values ('10','41');
insert into CONTIENE (NRO,COD_ART) values ('30','4');
insert into CONTIENE (NRO,COD_ART) values ('48','26');
insert into CONTIENE (NRO,COD_ART) values ('39','27');
insert into CONTIENE (NRO,COD_ART) values ('22','36');
insert into CONTIENE (NRO,COD_ART) values ('37','35');
insert into CONTIENE (NRO,COD_ART) values ('19','12');
insert into CONTIENE (NRO,COD_ART) values ('49','20');
insert into CONTIENE (NRO,COD_ART) values ('2','3');
insert into CONTIENE (NRO,COD_ART) values ('28','29');
insert into CONTIENE (NRO,COD_ART) values ('41','15');
insert into CONTIENE (NRO,COD_ART) values ('31','6');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('25','10');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('25','10');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('8','33');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('47','48');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('19','5');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('22','13');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('','20');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('','28');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('48','35');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('38','30');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('15','37');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('7','0');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('43','36');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('6','8');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('18','31');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('12','');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('26','24');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('4','46');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('0','18');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('13','44');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('21','16');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('35','6');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('44','45');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('5','9');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('28','43');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('39','15');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('16','2');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('34','1');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('27','19');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('32','3');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('11','26');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('41','22');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('33','12');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('10','38');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('9','25');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('1','23');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('3','41');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('2','42');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('31','27');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('23','14');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('14','11');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('42','4');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('17','32');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('36','21');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('24','');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('40','39');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('20','29');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('46','47');
insert into COMPUESTO_POR (COD_ART,COD_MAT) values ('37','40');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('6','37');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('6','37');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('38','33');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('2','28');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('42','');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('28','40');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('18','21');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('1','45');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('20','32');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('15','48');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('12','22');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('24','3');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('35','25');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('43','29');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('13','6');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('46','35');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('29','12');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('27','41');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('8','');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('40','20');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('11','14');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('39','27');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('16','24');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('21','18');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('33','17');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('0','11');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('45','26');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('36','39');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('48','1');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('3','16');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('30','7');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('10','');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('34','0');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('22','34');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('32','47');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('9','23');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('25','13');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('37','31');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('19','38');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('5','42');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('47','2');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('26','36');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('31','19');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('7','10');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('17','8');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('23','30');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('4','15');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('41','46');
insert into PROVISTO_POR (COD_MAT,COD_PROV) values ('44','43');
