insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (48,'Antonio','Koper');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (47,'Tomasa','Orouke');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (46,'Belinda','Barger');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (45,'Gladys','Laughery');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (44,'Ginger','Zorman');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (43,'Sabine','Bonaguidi');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (41,'Anton','Mew');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (42,'Annmarie','Esmay');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (38,'Ruthanne','Burgoyne');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (39,'Gisele','Limthong');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (40,'Benedict','Lavery');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (34,'Glenn','Mcgraff');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (35,'Antonia','Mclachlan');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (36,'Basil','Hanagan');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (37,'Anneliese','Namdar');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (27,'Bebe','Broadwell');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (28,'Florida','Gilliand');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (29,'Fran','Sibbald');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (30,'Becky','Falsetti');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (31,'Gilberto','Weibel');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (32,'Ruthe','Nishioka');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (33,'Belva','Old');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (16,'Tommy','Stoor');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (17,'Veronica','Aubrecht');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (18,'Beatris','Iraheta');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (19,'Gladis','Trevey');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (20,'Basil','Oursler');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (21,'Therese','Zaeske');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (22,'Bella','Osterfeld');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (23,'Francesco','Elland');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (24,'Bart','Detullio');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (25,'Wynona','Tenda');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (26,'Judson','Kantz');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (49,'Antonetta','Pinsky');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (0,'Theodora','Beavin');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (1,'Annetta','Juback');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (2,'Floy','Craver');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (3,'Tyrell','Zuelke');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (4,'Sabrina','Stojanovic');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (5,'Yvonne','Appleman');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (6,'Beau','Deerman');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (7,'Ty','Flournay');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (8,'Antoine','Applonie');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (9,'Belen','Ogden');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (10,'Vernita','Kulik');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (11,'Annice','Mccrossen');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (12,'Beata','Ladieu');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (13,'Toccara','Konwinski');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (14,'Julian','Rudack');
insert into "ALMACEN" ("NRO","NOMBRE","RESPONSABLE") values (15,'Ryan','Montori');
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (0,'Tank Top (Cyan) - M',8.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (1,'Polo Shirt (Cyan) - XL',34.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (2,'Plastic Storage Bin (Cyan) (2 Pack)',9.98);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (3,'Knit Hat (Cyan)',12.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (4,'Ankle Socks (Cyan) (12 Pack)',13.74);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (5,'Tank Top (Cyan) - S',8.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (6,'Crew Socks (Cyan) (12 Pack)',17.94);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (7,'Plastic Drawer Organizer (Cyan)',8.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (8,'Plastic Storage Bin (Cyan) (8 Pack)',39.92);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (9,'3 Ring Binder (Cyan) (8 Pack)',27.92);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (10,'Kitchen Floor Mat (Cyan) - L',12.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (11,'Crew Socks (Cyan) (6 Pack)',8.97);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (12,'Ankle Socks (Cyan) (6 Pack)',6.87);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (13,'Wire Bound Sketch Pad (Cyan)',11.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (14,'T-Shirt (Cyan) - XL',14.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (15,'3 Ring Binder (Cyan) (12 Pack)',41.88);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (16,'Small Notepad (Cyan)',7.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (17,'Kitchen Floor Mat (Cyan) - M',12.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (18,'Plastic Storage Bin (Cyan) (Single)',4.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (19,'Long Sleeve Flannel Shirt (Cyan) - M',21.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (20,'3 Ring Binder (Cyan) (4 Pack)',13.96);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (21,'Crew Socks (Cyan) (2 Pack)',2.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (22,'Tank Top (Cyan) - L',8.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (23,'Plastic Storage Bin (Cyan) (12 Pack)',59.88);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (24,'Zip-up Hoodie (Cyan) - S',49.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (25,'T-Shirt (Cyan) - S',14.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (26,'Polo Shirt (Cyan) - L',34.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (27,'3 Ring Binder (Cyan) (2 Pack)',6.98);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (28,'Zip-up Hoodie (Cyan) - XL',49.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (29,'Badminton Racket (Cyan)',15.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (30,'Tank Top (Cyan) - XL',8.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (31,'Golf Balls (Cyan) (10 Pack)',9.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (32,'Long Sleeve Flannel Shirt (Cyan) - L',21.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (33,'Long Sleeve Flannel Shirt (Cyan) - S',21.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (34,'Ankle Socks (Cyan) (2 Pack)',2.29);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (35,'Hardbound Sketch Book (Cyan)',15.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (36,'Kitchen Floor Mat (Cyan) - XL',12.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (37,'T-Shirt (Cyan) - M',14.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (38,'Kitchen Floor Mat (Cyan) - S',12.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (39,'Golf Balls (Cyan) (60 Pack)',59.94);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (40,'Polo Shirt (Cyan) - S',34.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (41,'Children''s Sippy Cup (Cyan)',6.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (42,'Long Sleeve Flannel Shirt (Cyan) - XL',21.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (43,'Polo Shirt (Cyan) - M',34.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (44,'3 Ring Binder (Cyan) (Single)',3.49);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (45,'Zip-up Hoodie (Cyan) - L',49.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (46,'T-Shirt (Cyan) - L',14.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (47,'Zip-up Hoodie (Cyan) - M',49.99);
insert into "ARTICULO" ("COD_ART","DESCRIPCION","PRECIO") values (48,'Golf Balls (Cyan) (30 Pack)',29.97);
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (0,'Technetium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (1,'Berkelium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (2,'Tungsten');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (3,'Thorium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (4,'Einsteinium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (5,'Ununquadium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (6,'Neptunium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (7,'Seaborgium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (8,'Plutonium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (9,'Rhenium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (10,'Uranium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (11,'Cadmium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (12,'Polonium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (13,'Ununpentium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (14,'Francium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (15,'Iridium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (16,'Palladium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (17,'Americium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (18,'Roentgenium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (19,'Gold');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (20,'Indium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (21,'Radium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (22,'Mendelevium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (23,'Lead');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (24,'Platinum');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (25,'Osmium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (26,'Hassium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (27,'Rhodium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (28,'Nobelium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (29,'Darmstadtium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (30,'Dubnium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (31,'Astatine');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (32,'Niobium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (33,'Lawrencium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (34,'Radon');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (35,'Ununtrium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (36,'Molybdenum');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (37,'Californium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (38,'Meitnerium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (39,'Bismuth');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (40,'Mercury');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (41,'Protactinium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (42,'Thallium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (43,'Curium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (44,'Fermium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (45,'Bohrium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (46,'Silver');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (47,'Ununbium');
insert into "MATERIAL" ("COD_MAT","DESCRIPCION") values (48,'Ruthenium');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (0,'Minneapolis');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (1,'Colorado Springs');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (2,'Black Hawk');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (3,'Helena');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (4,'Burbank');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (5,'Wolcott');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (6,'Wessington');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (7,'Burnsville');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (8,'Mesa');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (9,'Bighorn');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (10,'Sandy');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (11,'Ketchum');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (12,'Webster');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (13,'Lava Hot Springs');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (14,'Denver');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (15,'Coffee Creek');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (16,'West Yellowstone');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (17,'Algodones');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (18,'Kanab');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (19,'Tucson');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (20,'Boise');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (21,'Saint Cloud');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (22,'Coleridge');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (23,'Joliet');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (24,'Chino');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (25,'Eureka');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (26,'Leonard');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (27,'Ypsilanti');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (28,'Steamboat Springs');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (29,'Duluth');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (30,'Flaxton');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (31,'Chicago');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (32,'Star');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (33,'San Manuel');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (34,'Peever');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (35,'Cochiti Pueblo');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (36,'Cheyenne');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (37,'Medicine Bow');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (38,'Alamo');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (39,'Iroquois');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (40,'Rosebud');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (41,'Cayuga');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (42,'Sioux Falls');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (43,'Butte');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (44,'Saint Ignatius');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (45,'Yuma');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (46,'Hyrum');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (47,'Lisbon');
insert into "CIUDAD" ("COD_CIU","NOMBRE") values (48,'Red Valley');
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (0,'Zorman, Ginger','2515 SUMMER STREET','38',to_date('2012-03-21T02:52:58Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (1,'Beavin, Theodora','PO BOX 2210','42',to_date('2020-02-24T22:55:12Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (2,'Juback, Annetta','PO BOX 2829','25',to_date('1931-12-18T11:33:31Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (3,'Gilliand, Florida','123 S LINCOLN ST','18',to_date('1927-04-12T18:16:43Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (,'Weibel, Gilberto','SELECTMAN''S OFFICE','47',to_date('2016-07-19T20:55:26Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (5,'Barger, Belinda','PO BOX 60','45',to_date('1998-01-14T23:08:51Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (6,'Konwinski, Toccara','2301 PEGER ROAD','41',to_date('1981-08-20T18:49:33Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (7,'Mew, Anton','3375 AIRPORT ROAD','20',to_date('2007-12-18T10:32:42Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (8,'','2301 PEGER RD','5',to_date('1988-02-10T04:19:20Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (9,'Craver, Floy','3824 MOBERG DRIVE, STE. 101','7',to_date('2019-10-06T19:00:58Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (10,'Nishioka, Ruthe','BOX 1180','12',to_date('1977-03-28T08:53:23Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (11,'Falsetti, Becky','2301 PEGER RD','43',to_date('1957-08-03T15:29:11Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (12,'Flournay, Ty','PO BOX 112506','29',to_date('1974-05-22T05:40:18Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (13,'Sibbald, Fran','LEWISTON-NEZ PERCE COUNTY AIRPORT, 406 BURRELL AVE., SUITE 301','21',to_date('1986-05-28T05:53:19Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (14,'Mccrossen, Annice','6510 SE FORBES AVE #1','30',to_date('2004-12-17T13:03:05Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (15,'Osterfeld, Bella','1891-9TH ST/BROOKLEY COMPLEX','26',to_date('2011-07-31T16:34:37Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (16,'Appleman, Yvonne','CITY HALL','46',to_date('2002-02-16T09:59:28Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (17,'Rudack, Julian','2300 WEST WASHINGTON AVE','15',to_date('1935-02-03T08:22:35Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (18,'Limthong, Gisele','1960 JOE CROSSON DRIVE','24',to_date('2002-02-22T12:20:11Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (19,'Trevey, Gladis','2525 HWY 75, SUITE 301','17',to_date('1954-01-17T03:01:49Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (20,'Broadwell, Bebe','PO BOX 1898','32',to_date('2005-01-20T09:27:54Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (21,'Stojanovic, Sabrina','2301 PEGER RD','48',to_date('1931-04-25T23:10:27Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (22,'Lavery, Benedict','10 PUBLIC SQUARE','3',to_date('1925-06-28T15:43:16Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (23,'Deerman, Beau','2301 PEGER RD','40',to_date('1968-03-03T07:34:28Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (24,'Zaeske, Therese','HONOLULU INTL ARPT','23',to_date('2022-12-16T08:51:18Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (25,'Iraheta, Beatris','BOX 390','19',to_date('2022-04-18T01:34:54Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (26,'Laughery, Gladys','18374 PHANTOM','28',to_date('2012-11-18T02:25:01Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (27,'Burgoyne, Ruthanne','100 WEST WASHINGTON ST','13',to_date('1961-11-13T17:45:11Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (28,'Applonie, Antoine','11013 AIRPORT HWY','14',to_date('1998-01-13T18:49:59Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (29,'Kantz, Judson','425 N RICHARDSON','34',to_date('1942-04-25T15:43:11Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (30,'Pinsky, Antonetta','GOGEBIC CO COURTHOUSE, 200 N MOORE ST','35',to_date('1985-11-03T05:21:06Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (31,'Old, Belva','BOX 1059','44',to_date('1990-06-09T21:03:10Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (32,'Esmay, Annmarie','3800 AIRPORT ROAD, SUITE 209','9',to_date('1941-12-09T17:49:53Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (33,'Stoor, Tommy','PO BOX 158','6',to_date('2006-01-28T01:32:08Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (34,'Orouke, Tomasa','148 AVIATION LANE, SUITE 103','11',to_date('1950-02-03T21:19:58Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (35,'Tenda, Wynona','155 BURR STREET','39',to_date('2015-08-17T01:20:11Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (36,'Mclachlan, Antonia','8500 GARFIELD RD STE 101','27',to_date('1957-07-11T07:18:50Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (37,'Oursler, Basil','50 STATE ST, STE 7','0',to_date('2022-08-17T20:23:49Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (38,'Kulik, Vernita','1449 AIRPORT ROAD','2',to_date('2001-06-28T20:40:23Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (39,'Elland, Francesco','602 S. MAIN STREET','8',to_date('1933-08-21T06:43:12Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (40,'Montori, Ryan','1395 N US HIGHWAY 31','',to_date('1966-09-27T16:53:10Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (41,'Zuelke, Tyrell','55 INTERNATIONAL DRIVE','10',to_date('1987-05-22T14:02:28Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (42,'Detullio, Bart','ONE HARBORSIDE DR','37',to_date('1993-06-23T17:37:07Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (43,'Mcgraff, Glenn','2301 PEGER RD','31',to_date('1938-03-19T03:41:58Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (,'Bonaguidi, Sabine','1550 45TH AVE SE SUITE 1','4',to_date('1986-11-11T20:08:13Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (45,'Hanagan, Basil','6860 GLACIER HIGHWAY','16',to_date('1959-11-02T19:30:14Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (46,'Aubrecht, Veronica','','36',to_date('2000-06-30T16:37:01Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (47,'Ladieu, Beata','3250 W BRITT DAVID RD','33',to_date('1988-09-16T16:49:20Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "PROVEEDOR" ("COD_PROV","NOMBRE","DOMICILIO","COD_CIU","FECHA_ALTA") values (48,'Ogden, Belen','PO BOX 398','22',to_date('2006-12-15T12:18:23Z','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
insert into "CONTIENE" ("NRO","COD_ART") values ('27','38');
insert into "CONTIENE" ("NRO","COD_ART") values ('46','46');
insert into "CONTIENE" ("NRO","COD_ART") values ('17','32');
insert into "CONTIENE" ("NRO","COD_ART") values ('47','31');
insert into "CONTIENE" ("NRO","COD_ART") values ('38','0');
insert into "CONTIENE" ("NRO","COD_ART") values ('3','17');
insert into "CONTIENE" ("NRO","COD_ART") values ('23','42');
insert into "CONTIENE" ("NRO","COD_ART") values ('9','13');
insert into "CONTIENE" ("NRO","COD_ART") values ('6','2');
insert into "CONTIENE" ("NRO","COD_ART") values ('7','34');
insert into "CONTIENE" ("NRO","COD_ART") values ('45','19');
insert into "CONTIENE" ("NRO","COD_ART") values ('42','14');
insert into "CONTIENE" ("NRO","COD_ART") values ('40','9');
insert into "CONTIENE" ("NRO","COD_ART") values ('25','30');
insert into "CONTIENE" ("NRO","COD_ART") values ('29','18');
insert into "CONTIENE" ("NRO","COD_ART") values ('16','28');
insert into "CONTIENE" ("NRO","COD_ART") values ('21','25');
insert into "CONTIENE" ("NRO","COD_ART") values ('15','11');
insert into "CONTIENE" ("NRO","COD_ART") values ('35','47');
insert into "CONTIENE" ("NRO","COD_ART") values ('8','7');
insert into "CONTIENE" ("NRO","COD_ART") values ('32','43');
insert into "CONTIENE" ("NRO","COD_ART") values ('4','5');
insert into "CONTIENE" ("NRO","COD_ART") values ('43','40');
insert into "CONTIENE" ("NRO","COD_ART") values ('34','44');
insert into "CONTIENE" ("NRO","COD_ART") values ('1','10');
insert into "CONTIENE" ("NRO","COD_ART") values ('44','33');
insert into "CONTIENE" ("NRO","COD_ART") values ('20','8');
insert into "CONTIENE" ("NRO","COD_ART") values ('11','22');
insert into "CONTIENE" ("NRO","COD_ART") values ('14','21');
insert into "CONTIENE" ("NRO","COD_ART") values ('24','39');
insert into "CONTIENE" ("NRO","COD_ART") values ('12','45');
insert into "CONTIENE" ("NRO","COD_ART") values ('18','23');
insert into "CONTIENE" ("NRO","COD_ART") values ('33','24');
insert into "CONTIENE" ("NRO","COD_ART") values ('0','37');
insert into "CONTIENE" ("NRO","COD_ART") values ('36','16');
insert into "CONTIENE" ("NRO","COD_ART") values ('5','48');
insert into "CONTIENE" ("NRO","COD_ART") values ('13','1');
insert into "CONTIENE" ("NRO","COD_ART") values ('10','41');
insert into "CONTIENE" ("NRO","COD_ART") values ('30','4');
insert into "CONTIENE" ("NRO","COD_ART") values ('48','26');
insert into "CONTIENE" ("NRO","COD_ART") values ('39','27');
insert into "CONTIENE" ("NRO","COD_ART") values ('22','36');
insert into "CONTIENE" ("NRO","COD_ART") values ('37','35');
insert into "CONTIENE" ("NRO","COD_ART") values ('19','12');
insert into "CONTIENE" ("NRO","COD_ART") values ('49','20');
insert into "CONTIENE" ("NRO","COD_ART") values ('2','3');
insert into "CONTIENE" ("NRO","COD_ART") values ('28','29');
insert into "CONTIENE" ("NRO","COD_ART") values ('41','15');
insert into "CONTIENE" ("NRO","COD_ART") values ('31','6');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('25','10');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('25','10');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('8','33');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('47','48');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('19','5');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('22','13');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('','20');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('','28');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('48','35');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('38','30');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('15','37');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('7','0');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('43','36');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('6','8');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('18','31');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('12','');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('26','24');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('4','46');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('0','18');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('13','44');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('21','16');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('35','6');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('44','45');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('5','9');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('28','43');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('39','15');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('16','2');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('34','1');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('27','19');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('32','3');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('11','26');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('41','22');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('33','12');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('10','38');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('9','25');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('1','23');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('3','41');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('2','42');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('31','27');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('23','14');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('14','11');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('42','4');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('17','32');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('36','21');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('24','');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('40','39');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('20','29');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('46','47');
insert into "COMPUESTO_POR" ("COD_ART","COD_MAT") values ('37','40');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('6','37');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('6','37');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('38','33');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('2','28');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('42','');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('28','40');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('18','21');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('1','45');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('20','32');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('15','48');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('12','22');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('24','3');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('35','25');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('43','29');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('13','6');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('46','35');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('29','12');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('27','41');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('8','');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('40','20');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('11','14');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('39','27');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('16','24');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('21','18');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('33','17');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('0','11');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('45','26');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('36','39');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('48','1');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('3','16');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('30','7');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('10','');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('34','0');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('22','34');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('32','47');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('9','23');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('25','13');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('37','31');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('19','38');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('5','42');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('47','2');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('26','36');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('31','19');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('7','10');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('17','8');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('23','30');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('4','15');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('41','46');
insert into "PROVISTO_POR" ("COD_MAT","COD_PROV") values ('44','43');
